import type { ScreeningAnswers } from "./pt-programming";

export const caseStudyFixtures = {
  ciara: { name: "Ciara", age: 27, sex: "Female", heightCm: 167, weightKg: 68, goal: "Fat loss and tone", experience: "beginner", trainingDays: 3, sessionDurationMinutes: 60, location: "Commercial gym", locationType: "Full gym", equipment: ["Dumbbells", "Machines", "Cable", "Cross trainer", "Treadmill"], screening: {} as ScreeningAnswers, notes: "Module 7 case study. Frequent gym goer with five years of attendance, but low confidence using weights. Works 50+ hours across changing shifts and reports high daily step count. Attends two gym classes and dislikes running. Goals: three gym sessions weekly, 5 km under 30 minutes in 12 weeks, and reduce body-fat percentage from 29% to below 25% over six months. Fitness results include fair press-up capacity, restricted shoulder/neck mobility and 30 kg 10RM barbell squat." },
  jessica: { name: "Jessica", age: 23, sex: "Female", heightCm: 172, weightKg: 65, goal: "Power gain", experience: "advanced", trainingDays: 3, sessionDurationMinutes: 75, location: "Athletics club and gym", locationType: "Full gym", equipment: ["Barbell", "Dumbbells", "Rack", "Cable", "Plyometric equipment"], screening: { injuryOrMusculoskeletalLimitation: true } as ScreeningAnswers, notes: "Module 7 case study. 100 m hurdles and long-jump athlete, with three gym sessions and two athletics sessions weekly. Ankle sprain approximately six weeks ago; reports difficulty reaching a low squat/snatch position and wants cautious loading. Goals: add 5 kg to a 115 kg deadlift 1RM and improve vertical jump from 55 cm to over 60 cm." },
  kevin: { name: "Kevin", age: 21, sex: "Male", heightCm: 178, weightKg: 72, goal: "Strength gain", experience: "intermediate", trainingDays: 5, sessionDurationMinutes: 60, location: "Commercial gym", locationType: "Full gym", equipment: ["Barbell", "Rack", "Dumbbells", "Cable", "Machines"], screening: {} as ScreeningAnswers, notes: "Module 7 case study. Final-year computer-science student with recent consistent training after a sporadic start. Five gym days available, with football strains reported historically but no current medical condition or recent injury. Main goal is high-bar back-squat strength with possible powerlifting competition. Baselines: squat 5RM 110 kg, bench 1RM 92.5 kg and deadlift 1RM 155 kg." },
  paul: { name: "Paul", age: 61, sex: "Male", heightCm: 183, weightKg: 83, goal: "Muscle and strength gain", experience: "beginner", trainingDays: 2, sessionDurationMinutes: 60, location: "Commercial gym", locationType: "Full gym", equipment: ["Machines", "Dumbbells", "Cable", "Bike"], screening: { injuryOrMusculoskeletalLimitation: true, cardiovascularHistory: true } as ScreeningAnswers, notes: "Module 7 case study. Retired, walks 30–60 minutes most days and wants to regain strength and muscle. Long history of back pain associated with factory work and prolonged sitting; previous pre-hypertension, with GP-confirmed normal blood pressure since retirement. Goals: improve sit-and-reach from 29 cm to over 30 cm, press-ups from 5 to 10+ and build a consistent two-to-three-day resistance-training habit." },
} as const;

export type CaseStudySlug = keyof typeof caseStudyFixtures;
