import { and, asc, desc, eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";

import { designerOwnership, isActiveOwner, requireOwner } from "@/lib/authorization/require-owner";
import { getDb } from "@/lib/db/client";
import { getCurrentProgrammeQuality } from "@/lib/pt-quality-server";
import { buildClientTimeline } from "@/lib/pt-client-timeline";
import { readAssessmentNotes } from "@/lib/pt-data";
import { ptAssessments, ptClientPerformanceRecords, ptClients, ptExercisePrescriptions, ptExercises, ptGoals, ptLocations, ptPreferences, ptProgrammeEvents, ptProgrammeQualityReviews, ptProgrammeWeeks, ptProgrammes, ptSessions, ptWorkoutResults } from "@/lib/db/schema";

export const dynamic = "force-dynamic";

export async function GET(request: NextRequest) {
  const owner = await requireOwner();
  if (!isActiveOwner(owner)) return owner;
  const access = { state: "active" as const, account: owner };
  const clientId = request.nextUrl.searchParams.get("clientId");
  if (!clientId) return NextResponse.json({ error: "clientId is required" }, { status: 400 });
  const db = getDb();
  const requestedWeek = Number(request.nextUrl.searchParams.get("weekNumber"));
  const [client] = await db.select({ id: ptClients.id, firstName: ptClients.firstName, lastName: ptClients.lastName, clientColour: ptClients.clientColour, dateOfBirth: ptClients.dateOfBirth, sexOrGender: ptClients.sexOrGender, trainingExperience: ptClients.trainingExperience, heightCm: ptClients.heightCm, weightKg: ptClients.weightKg, occupation: ptClients.occupation, dailyActivity: ptClients.dailyActivity, sessionDurationMinutes: ptClients.sessionDurationMinutes, preferredDays: ptClients.preferredDays, sleepHours: ptClients.sleepHours, stressLevel: ptClients.stressLevel, notes: ptClients.notes, createdAt: ptClients.createdAt, updatedAt: ptClients.updatedAt }).from(ptClients).where(and(eq(ptClients.id, clientId), designerOwnership(ptClients.ownerProfileId, owner))).limit(1);
  if (!client) return NextResponse.json({ error: "Client not found" }, { status: 404 });
  const assessmentRows = await db.select({ id: ptAssessments.id, clearanceRequired: ptAssessments.clearanceRequired, riskFlags: ptAssessments.riskFlags, responses: ptAssessments.responses, reviewDate: ptAssessments.reviewDate, assessmentDate: ptAssessments.assessmentDate, ptNotes: ptAssessments.ptNotes, createdAt: ptAssessments.createdAt, updatedAt: ptAssessments.updatedAt }).from(ptAssessments).where(eq(ptAssessments.clientId, client.id)).orderBy(desc(ptAssessments.assessmentDate), desc(ptAssessments.updatedAt));
  const [assessmentRow] = assessmentRows;
  const assessment = assessmentRow ? { ...assessmentRow, ...readAssessmentNotes(assessmentRow.responses) } : null;
  const goalRows = await db.select({ id: ptGoals.id, goalType: ptGoals.goalType, priority: ptGoals.priority, target: ptGoals.target, metric: ptGoals.metric, createdAt: ptGoals.createdAt, updatedAt: ptGoals.updatedAt }).from(ptGoals).where(eq(ptGoals.clientId, client.id)).orderBy(desc(ptGoals.updatedAt));
  const [goal] = goalRows.filter((item) => item.priority === "primary");
  const locationRows = await db.select({ id: ptLocations.id, name: ptLocations.name, locationType: ptLocations.locationType, equipment: ptLocations.equipment, createdAt: ptLocations.createdAt, updatedAt: ptLocations.updatedAt }).from(ptLocations).where(eq(ptLocations.clientId, client.id)).orderBy(desc(ptLocations.updatedAt));
  const [location] = locationRows;
  const preferenceRows = await db.select({ id: ptPreferences.id, likedExercises: ptPreferences.likedExercises, dislikedExercises: ptPreferences.dislikedExercises, preferredStyle: ptPreferences.preferredStyle, preferredStructure: ptPreferences.preferredStructure, preferredEquipment: ptPreferences.preferredEquipment, cardioModalities: ptPreferences.cardioModalities, varietyPreference: ptPreferences.varietyPreference, confidenceNotes: ptPreferences.confidenceNotes, createdAt: ptPreferences.createdAt, updatedAt: ptPreferences.updatedAt }).from(ptPreferences).where(eq(ptPreferences.clientId, client.id)).limit(1);
  const [preferences] = preferenceRows;
  const performanceRecords = await db.select({ id: ptClientPerformanceRecords.id, exerciseId: ptClientPerformanceRecords.exerciseId, exerciseName: ptExercises.name, metricType: ptClientPerformanceRecords.metricType, metricName: ptClientPerformanceRecords.metricName, performanceDate: ptClientPerformanceRecords.performanceDate, value: ptClientPerformanceRecords.value, unit: ptClientPerformanceRecords.unit, repetitions: ptClientPerformanceRecords.repetitions, loadKg: ptClientPerformanceRecords.loadKg, source: ptClientPerformanceRecords.source, confidence: ptClientPerformanceRecords.confidence, techniqueAcceptable: ptClientPerformanceRecords.techniqueAcceptable, painReported: ptClientPerformanceRecords.painReported, notes: ptClientPerformanceRecords.notes, createdAt: ptClientPerformanceRecords.createdAt, updatedAt: ptClientPerformanceRecords.updatedAt }).from(ptClientPerformanceRecords).leftJoin(ptExercises, eq(ptClientPerformanceRecords.exerciseId, ptExercises.id)).where(eq(ptClientPerformanceRecords.clientId, client.id)).orderBy(desc(ptClientPerformanceRecords.performanceDate), desc(ptClientPerformanceRecords.createdAt)).limit(100);
  const programmeHistory = await db.select({ id: ptProgrammes.id, name: ptProgrammes.name, goalSummary: ptProgrammes.goalSummary, status: ptProgrammes.status, version: ptProgrammes.version, updatedAt: ptProgrammes.updatedAt, createdAt: ptProgrammes.createdAt }).from(ptProgrammes).where(and(eq(ptProgrammes.clientId, client.id), designerOwnership(ptProgrammes.ownerProfileId, owner))).orderBy(desc(ptProgrammes.version));
  const [programme] = await db.select({ id: ptProgrammes.id, name: ptProgrammes.name, goalSummary: ptProgrammes.goalSummary, status: ptProgrammes.status, currentWeek: ptProgrammes.currentWeek, durationWeeks: ptProgrammes.durationWeeks, version: ptProgrammes.version, rationale: ptProgrammes.rationale }).from(ptProgrammes).where(and(eq(ptProgrammes.clientId, client.id), designerOwnership(ptProgrammes.ownerProfileId, owner))).orderBy(desc(ptProgrammes.updatedAt)).limit(1);
  const programmeEvents = await db.select({ id: ptProgrammeEvents.id, programmeId: ptProgrammeEvents.programmeId, programmeName: ptProgrammes.name, action: ptProgrammeEvents.action, details: ptProgrammeEvents.details, createdAt: ptProgrammeEvents.createdAt }).from(ptProgrammeEvents).innerJoin(ptProgrammes, eq(ptProgrammeEvents.programmeId, ptProgrammes.id)).where(and(eq(ptProgrammes.clientId, client.id), eq(ptProgrammes.ownerProfileId, access.account.authUserId))).orderBy(desc(ptProgrammeEvents.createdAt));
  const qualityReviews = await db.select({ id: ptProgrammeQualityReviews.programmeId, programmeId: ptProgrammeQualityReviews.programmeId, programmeName: ptProgrammes.name, score: ptProgrammeQualityReviews.score, approvalReadiness: ptProgrammeQualityReviews.approvalReadiness, blockingCount: ptProgrammeQualityReviews.blockingCount, significantCount: ptProgrammeQualityReviews.significantCount, advisoryCount: ptProgrammeQualityReviews.advisoryCount, evidenceVersion: ptProgrammeQualityReviews.evidenceVersion, evaluatedAt: ptProgrammeQualityReviews.evaluatedAt }).from(ptProgrammeQualityReviews).innerJoin(ptProgrammes, eq(ptProgrammeQualityReviews.programmeId, ptProgrammes.id)).where(and(eq(ptProgrammes.clientId, client.id), eq(ptProgrammes.ownerProfileId, access.account.authUserId))).orderBy(desc(ptProgrammeQualityReviews.evaluatedAt));
  const workoutResults = await db.select({ id: ptWorkoutResults.id, scheduledDate: ptWorkoutResults.scheduledDate, sessionName: ptSessions.name, status: ptWorkoutResults.status, sessionRpe: ptWorkoutResults.sessionRpe, energy: ptWorkoutResults.energy, painReported: ptWorkoutResults.painReported, notes: ptWorkoutResults.notes, createdAt: ptWorkoutResults.createdAt, updatedAt: ptWorkoutResults.updatedAt }).from(ptWorkoutResults).leftJoin(ptSessions, eq(ptWorkoutResults.sessionId, ptSessions.id)).where(and(eq(ptWorkoutResults.clientId, client.id), eq(ptWorkoutResults.ownerProfileId, access.account.authUserId))).orderBy(desc(ptWorkoutResults.scheduledDate), desc(ptWorkoutResults.createdAt)).limit(100);
  const timeline = buildClientTimeline({ client, assessments: assessmentRows, goals: goalRows, locations: locationRows, preferences: preferenceRows, programmes: programmeHistory, qualityReviews, programmeEvents, workouts: workoutResults, performance: performanceRecords });
  if (!programme) return NextResponse.json({ client, assessment: assessment ?? null, goal: goal ?? null, location: location ?? null, preferences: preferences ?? null, performanceRecords, programmeHistory, timeline, programme: null, quality: null });
  const quality = await getCurrentProgrammeQuality(db, access.account.authUserId, programme.id);
  const events = programmeEvents.filter((event) => event.programmeId === programme.id).map(({ id, action, details, createdAt }) => ({ id, action, details, createdAt }));
  const selectedWeekNumber = Number.isInteger(requestedWeek) && requestedWeek >= 1 && requestedWeek <= programme.durationWeeks ? requestedWeek : programme.currentWeek;
  const [week] = await db.select({ id: ptProgrammeWeeks.id, weekNumber: ptProgrammeWeeks.weekNumber, focus: ptProgrammeWeeks.focus, volumeTarget: ptProgrammeWeeks.volumeTarget, intensityTarget: ptProgrammeWeeks.intensityTarget }).from(ptProgrammeWeeks).where(and(eq(ptProgrammeWeeks.programmeId, programme.id), eq(ptProgrammeWeeks.weekNumber, selectedWeekNumber))).limit(1);
  const weekOptions = await db.select({ weekNumber: ptProgrammeWeeks.weekNumber, focus: ptProgrammeWeeks.focus, volumeTarget: ptProgrammeWeeks.volumeTarget, intensityTarget: ptProgrammeWeeks.intensityTarget }).from(ptProgrammeWeeks).where(eq(ptProgrammeWeeks.programmeId, programme.id)).orderBy(ptProgrammeWeeks.weekNumber);
  const sessions = week ? await db.select({ id: ptSessions.id, dayOfWeek: ptSessions.dayOfWeek, scheduledTime: ptSessions.scheduledTime, managementMode: ptSessions.managementMode, name: ptSessions.name, sessionType: ptSessions.sessionType, durationMinutes: ptSessions.durationMinutes, exerciseId: ptExercises.id, exerciseName: ptExercises.name, pattern: ptExercises.movementPattern, target: ptExercises.primaryMuscles, equipment: ptExercises.equipment, prescriptionId: ptExercisePrescriptions.id, orderIndex: ptExercisePrescriptions.orderIndex, sets: ptExercisePrescriptions.sets, repsMin: ptExercisePrescriptions.repsMin, repsMax: ptExercisePrescriptions.repsMax, intensityValue: ptExercisePrescriptions.intensityValue, restSeconds: ptExercisePrescriptions.restSeconds, tempo: ptExercisePrescriptions.tempo, progressionRule: ptExercisePrescriptions.progressionRule, technique: ptExercisePrescriptions.technique, notes: ptExercisePrescriptions.notes }).from(ptSessions).leftJoin(ptExercisePrescriptions, eq(ptExercisePrescriptions.sessionId, ptSessions.id)).leftJoin(ptExercises, eq(ptExercises.id, ptExercisePrescriptions.exerciseId)).where(eq(ptSessions.programmeWeekId, week.id)).orderBy(asc(ptSessions.dayOfWeek), asc(ptExercisePrescriptions.orderIndex)) : [];
  const sessionMap = new Map<string, { id: string; dayOfWeek: number; scheduledTime: string | null; managementMode: "pt_managed" | "self_managed"; name: string; sessionType: string; durationMinutes: number; exercises: Array<{ name: string; pattern: string; prescription: string; target: string; equipment: string; exerciseId: string; prescriptionId: string; sets: number; repsMin?: number; repsMax?: number; intensityValue?: string; restSeconds?: number; tempo?: string; progressionRule?: string; method?: string; note?: string }> }>();
  for (const row of sessions) {
    const current = sessionMap.get(row.id) ?? { id: row.id, dayOfWeek: row.dayOfWeek, scheduledTime: row.scheduledTime, managementMode: row.managementMode, name: row.name, sessionType: row.sessionType, durationMinutes: row.durationMinutes, exercises: [] };
    if (row.exerciseName && row.pattern && row.sets && row.prescriptionId && row.exerciseId) current.exercises.push({ name: row.exerciseName, pattern: row.pattern, prescription: row.repsMin ? `${row.sets} × ${row.repsMin}${row.repsMax && row.repsMax !== row.repsMin ? `–${row.repsMax}` : ""}` : `${row.sets} sets`, target: Array.isArray(row.target) ? row.target.join(" · ") : "", equipment: Array.isArray(row.equipment) ? row.equipment.join(", ") : "", exerciseId: row.exerciseId, prescriptionId: row.prescriptionId, sets: row.sets, repsMin: row.repsMin ?? undefined, repsMax: row.repsMax ?? undefined, intensityValue: row.intensityValue ?? undefined, restSeconds: row.restSeconds ?? undefined, tempo: row.tempo ?? undefined, progressionRule: row.progressionRule ?? undefined, method: row.technique ?? undefined, note: row.notes ?? undefined });
    sessionMap.set(row.id, current);
  }
  return NextResponse.json({ client, assessment: assessment ?? null, goal: goal ?? null, location: location ?? null, preferences: preferences ?? null, performanceRecords, programmeHistory, timeline, quality: quality?.review ?? null, programme: { ...programme, week: week ?? null, weekOptions, sessions: Array.from(sessionMap.values()), events } });
}
